In [2]:
import pandas as pd
df=pd.read_csv('input.txt',header=None)
df = df[0].apply(lambda x: pd.Series(list(x)))
df

   0  1  2  3  4  5  6  7  8  9   ... 86 87 88 89 90 91 92 93 94 95
0   L  L  L  L  L  L  .  L  L  L  ...  L  L  L  L  L  L  L  L  L  L
1   L  L  L  L  L  L  L  L  L  L  ...  L  L  L  L  L  L  L  L  L  L
2   L  L  L  L  L  L  .  L  L  L  ...  L  L  L  L  L  L  L  L  L  L
3   L  L  L  L  L  L  .  L  L  L  ...  L  L  L  L  .  L  L  .  L  L
4   L  L  L  L  L  L  .  L  L  L  ...  L  L  L  L  L  L  L  L  L  L
.. .. .. .. .. .. .. .. .. .. ..  ... .. .. .. .. .. .. .. .. .. ..
94  L  L  L  L  L  L  .  L  L  L  ...  L  L  L  L  .  L  L  L  L  L
95  L  L  L  L  L  L  .  L  L  L  ...  L  L  L  L  .  L  L  L  L  L
96  L  L  L  L  L  L  L  L  L  L  ...  L  L  L  L  .  L  L  L  L  L
97  L  L  L  L  L  L  .  L  L  L  ...  L  L  L  L  L  L  L  L  L  L
98  L  .  L  L  L  L  L  L  L  L  ...  L  L  L  L  .  L  L  L  L  L

[99 rows x 96 columns]

In [3]:
EMPTY = 'L'
FULL = '#'
def check_surrounding_seats(input_df,row,col):
    temp = input_df.iloc[row,col]
    input_df.iloc[row,col] = '' #ignore actual seat cell
    #max (0,X) for left and upper edges (can handle ending edges)
    adj_block = input_df.iloc[max(0,(row-1)):(row+2),max(0,(col-1)):(col+2)]
    full_count = adj_block[adj_block == FULL].count().sum()
    input_df.iloc[row,col] = temp
    return full_count

def fill_seats(input_df):
    temp_copy = input_df.copy(deep=True)
    input_df
    for row_idx, row in input_df.iterrows():
        for col_idx, col in row.iteritems():
            if(temp_copy.iloc[row_idx,col_idx] == EMPTY):
                if(check_surrounding_seats(input_df,row_idx,col_idx) == 0):
                    temp_copy.iloc[row_idx,col_idx] = FULL
    return temp_copy

def remove_seats(input_df):
    temp_copy = input_df.copy(deep=True)
    for row_idx, row in input_df.iterrows():
        for col_idx, col in row.iteritems():
            if(temp_copy.iloc[row_idx,col_idx] == FULL):
                if(check_surrounding_seats(input_df,row_idx,col_idx) >= 4):
                    temp_copy.iloc[row_idx,col_idx] = EMPTY
    return temp_copy

In [5]:
count = 0
while(True):
    print(f'Iteration: {count}')
    s1 = fill_seats(df)
    s2 = remove_seats(s1)
    mismatches = (s2 != s1).sum().sum()
    if(mismatches == 0):
        break
    df = s2
    count += 1
    print(f'Mismatches: {mismatches}')

Iteration: 0
Mismatches: 7666
Iteration: 1
Mismatches: 7099
Iteration: 2
Mismatches: 6546
Iteration: 3
Mismatches: 6026
Iteration: 4
Mismatches: 5592
Iteration: 5
Mismatches: 5174
Iteration: 6
Mismatches: 4790
Iteration: 7
Mismatches: 4468
Iteration: 8
Mismatches: 4161
Iteration: 9
Mismatches: 3860
Iteration: 10
Mismatches: 3539
Iteration: 11
Mismatches: 3251
Iteration: 12
Mismatches: 2966
Iteration: 13
Mismatches: 2699
Iteration: 14
Mismatches: 2467
Iteration: 15
Mismatches: 2258
Iteration: 16
Mismatches: 2067
Iteration: 17
Mismatches: 1859
Iteration: 18
Mismatches: 1658
Iteration: 19
Mismatches: 1487
Iteration: 20
Mismatches: 1323
Iteration: 21
Mismatches: 1171
Iteration: 22
Mismatches: 1057
Iteration: 23
Mismatches: 970
Iteration: 24
Mismatches: 890
Iteration: 25
Mismatches: 823
Iteration: 26
Mismatches: 748
Iteration: 27
Mismatches: 674
Iteration: 28
Mismatches: 607
Iteration: 29
Mismatches: 539
Iteration: 30
Mismatches: 490
Iteration: 31
Mismatches: 446
Iteration: 32
Mismatches: 412
Iteration: 33
Mismatches: 383
Iteration: 34
Mismatches: 354
Iteration: 35
Mismatches: 321
Iteration: 36
Mismatches: 285
Iteration: 37
Mismatches: 242
Iteration: 38
Mismatches: 196
Iteration: 39
Mismatches: 148
Iteration: 40
Mismatches: 104
Iteration: 41
Mismatches: 88
Iteration: 42
Mismatches: 73
Iteration: 43
Mismatches: 60
Iteration: 44
Mismatches: 44
Iteration: 45
Mismatches: 22
Iteration: 46
Mismatches: 6
Iteration: 47

In [6]:
(s2 == FULL).sum().sum()

2424